### ISSUE TITLE
HW feedback

### ISSUE THREAD

**Issue by rfaroul** [E-Hizzle/week-3-game#1]
Your game is siiiiiick.

Put your javascript code in a .js file. And link to it using a script tag in your html file. It should be at the bottom of the html file (so that it loads last, after your html and css have loaded) and should look like this:

<script type="text/javascript" href="hangman.js"></script>

You've got great code structure and a good understanding of how to lay out your steps.

The next homework assignment is similar to hangman in a lot of ways. Think about how you could've used objects in this assignment and try to implement them in the next hw assignment.

I want you to add one feature: when a player fails to guess the word, display the word with the "You lose" message.

Awesome work!

**Comment by theWallsOfEricHo** [comment]
Thank you!
